template = "https://github.com/giellalt/template-lang-und"
rev_id = 314
template_sha = "f0f8f02f628669553dfb6ab472bf9a2451d4a18d"

[replacements]
__GLOTTOLOG_ID__ = "zulu1248"
__REPO__ = "lang-zul-x-exp"
__UND2C__ = "zu"
__UNDEFINED__ = "Zulu"
__UND__ = "zul"
