template = "https://github.com/giellalt/template-lang-und"
rev_id = 300
template_sha = "0371712ab0950051a69847be792b3ad6c2a463ac"

[replacements]
__GLOTTOLOG_ID__ = "zulu1248"
__REPO__ = "lang-zul-x-exp"
__UND2C__ = "zu"
__UNDEFINED__ = "Zulu"
__UND__ = "zul"
