[package]
name = "zul"
human_name = "Zulu"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.zul]
filename = "zu-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-zul"
platform = "windows"
uuid = "C28CEEFA-5BA5-40BD-B2D5-77D5A968665B"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.zu"
package = "speller-zul"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-zul-mso"
platform = "windows"
uuid = "B03EE16A-5372-492B-B672-D675C94C92B6"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-zul"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
